command:
  no-permission: "&cYou do not have permission to use this command."
  toggle:
    enabled: "&aChatGPT has connected. Say Hi!"
    disabled: "&cChatGPT has disconnected."
  format:
    - "&bYou: &7%message%"
    - "&bAI: &a%message%"
  error: "&cAn error occurred while processing your message."

# https://beta.openai.com/account/api-keys
API_KEY: ""